%%find the mean and std of duration of states referred by stateIndex.
%duration of a state means the number of times it has occured consecutively while traversing a list(say, list of states generated by random walk). The mean and std are central tendencies of samples collected from complete list traversal.
function durationMap = computeDurationOfStates(simulatedStates)
	clear durationMap;
	durationMap = containers.Map('KeyType', 'double', 'ValueType','any');
	jj = 1; kk = 1;
	while jj <= length(simulatedStates); 
		state = simulatedStates(jj);
		kk = jj+1;
		while kk <=length(simulatedStates);  
		  if state ~= simulatedStates(kk);
		    break;
		  end
		  kk = kk + 1;
		end
		count = kk-jj;
		if ~isKey(durationMap, state);
		 durationMap(state) = [];
		end
		prev = durationMap(state);
		durationMap(state) = [prev, count];
		jj = kk; %move the seek forward
	end
end

